style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    max: 4

complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true


formatting:
  FinalNewline:
    active: false


performance:
  SpreadOperator:
    active: false

