style:
  NewLineAtEndOfFile:
    active: false


complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true
  NestedBlockDepth:
    threshold: 6


    
formatting:
  FinalNewline:
    active: false

performance:
  SpreadOperator:
    active: false

